services:
  backend:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8000
    ports:
      - "8000:8000"
    restart: always

  web:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.frontend
    ports:
      - "3000:3000"
    restart: always
