FROM oven/bun

WORKDIR /app

COPY package.json bun.lock turbo.json ./
COPY packages/db/package.json ./packages/db/package.json
COPY packages/zod/package.json ./packages/zod/package.json
COPY apps/backend/package.json ./apps/backend/package.json

RUN bun install

COPY packages ./packages
COPY apps/backend ./apps/backend

WORKDIR /app/packages/db
RUN bun x prisma generate

WORKDIR /app

EXPOSE 8000

CMD ["bun", "run", "apps/backend/index.ts"]
